apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base]
namespace: smartboxx-client-production
labels:
  - pairs: { smartboxx.io/environment: client-production, smartboxx.io/platform-version: 0.1.0 }
