apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base]
namespace: smartboxx-client-test
labels:
  - pairs: { smartboxx.io/environment: client-test, smartboxx.io/platform-version: 0.1.0 }
